[package]
name = "starryconfig"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
miette = { version = "7.6.0" }
starryparse= { version="1.0.1", features=["miette"] }
thiserror = "2.0.18"
starryconfig_derive = { path="../starryconfig_derive", optional=true }

[features]
default=["derive"]
derive=["dep:starryconfig_derive"]

