[package]
name = "starryconfig_test"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[dependencies]
miette={version="7.6.0", features=["fancy"]}
starryconfig={path="../starryconfig", features=["derive"]}
kdl={version="6.5.0"}
knus="3.4.0"
